# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projectA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for projectA 
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.0’
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod 'HCSStarRatingView', '~> 1.5'
pod 'PFNavigationDropdownMenu'

  target 'projectATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
